export const FETCH_SEARCH_BY_QUERY_REQUEST = 'FETCH_SEARCH_BY_QUERY_REQUEST'
export const FETCH_SEARCH_BY_QUERY_SUCCESS = 'FETCH_SEARCH_BY_QUERY_SUCCESS'
export const FETCH_SEARCH_BY_QUERY_FAILURE = 'FETCH_SEARCH_BY_QUERY_FAILURE'

export const FETCH_SEARCH_BY_AUTHOR_REQUEST = 'FETCH_SEARCH_BY_AUTHOR_REQUEST'
export const FETCH_SEARCH_BY_AUTHOR_SUCCESS = 'FETCH_SEARCH_BY_AUTHOR_SUCCESS'
export const FETCH_SEARCH_BY_AUTHOR_FAILURE = 'FETCH_SEARCH_BY_AUTHOR_FAILURE'

export const FETCH_SEARCH_BY_TAG_REQUEST = 'FETCH_SEARCH_BY_TAG_REQUEST'
export const FETCH_SEARCH_BY_TAG_SUCCESS = 'FETCH_SEARCH_BY_TAG_SUCCESS'
export const FETCH_SEARCH_BY_TAG_FAILURE = 'FETCH_SEARCH_BY_TAG_FAILURE'

export const FETCH_QUESTION_REQUEST = 'FETCH_QUESTION_REQUEST'
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS'
export const FETCH_QUESTION_FAILURE = 'FETCH_QUESTION_FAILURE'
